include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude: [build/**]

#  enable-experiment:
#    - non-nullable

  strong-mode:
    implicit-casts: true
    implicit-dynamic: false

  errors:
    missing_enum_constant_in_switch: error
    no_duplicate_case_values: warning

linter:
  rules:
    - camel_case_types
