name: Xyz
description: Xyz

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-19.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.1
  provider: ^4.1.0-dev+3
  pedantic: ^1.9.0

flutter:

  # include Material icons with application
  uses-material-design: true

#  assets:

#  fonts:
